export const data = [
  {
    name: "yunchir",
    status: "none",
    password: "yunchir",
    role: true,
  },
  {
    name: "uka",
    status: "active",
    password: "uka",
    role: true,
  },
  {
    name: "yalalt",
    status: "none",
    password: "yalalt",
    role: true,
  },
  {
    name: "murun",
    status: "none",
    password: "murun",
    role: true,
  },
  {
    name: "baynaa",
    status: "none",
    password: "baynaa",
    role: true,
  },
  {
    name: "suld",
    status: "none",
    password: "suld",
    role: true,
  },
  {
    name: "sharaw",
    status: "none",
    password: "sharaw",
    role: true,
  },
  {
    name: "suhee",
    status: "none",
    password: "suhee",
    role: true,
  },
  {
    name: "naraa",
    status: "none",
    password: "naraa",
    role: true,
  },
  {
    name: "nomin",
    status: "none",
    password: "nomin",
    role: true,
  },
  {
    name: "nergvi",
    status: "none",
    password: "nergvi",
    role: true,
  },
  {
    name: "usuh",
    status: "none",
    password: "usuh",
    role: true,
  },
  {
    name: "tuga",
    status: "none",
    password: "tuga",
    role: true,
  },
  {
    name: "bat",
    status: "none",
    password: "bat",
    role: true,
  },
  {
    name: "namka",
    status: "none",
    password: "namka",
    role: true,
  },
  {
    name: "jemmy",
    status: "none",
    password: "jemmy",
    role: true,
  },
  {
    name: "maral",
    status: "none",
    password: "maral",
    role: true,
  },
  {
    name: "tuul",
    status: "none",
    password: "tuul",
    role: true,
  },
  {
    name: "baljka",
    status: "none",
    password: "baljka",
    role: true,
  },
  {
    name: "batmyn",
    status: "none",
    password: "batmyn",
    role: true,
  },

  {
    name: "andy",
    status: "none",
    password: "andy",
    role: false,
  },

  {
    name: "orgil",
    status: "none",
    password: "orgil",
    role: false,
  },
];
